package woodcalculator;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Sabau Ionut
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel_title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_fullname1 = new javax.swing.JLabel();
        jLabel_backToLogin = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jPanel_minimize = new javax.swing.JPanel();
        jLabel_minimize = new javax.swing.JLabel();
        jPanel_login_form = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jPasswordField_confirmpassword = new javax.swing.JPasswordField();
        jButton_register = new javax.swing.JButton();
        jLabel_fullname = new javax.swing.JLabel();
        jTextField_fullname = new javax.swing.JTextField();
        jLabel_password = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jLabel_telefon = new javax.swing.JLabel();
        jTextField_telefon = new javax.swing.JTextField();
        jLabel_confirmpassword = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 136, 122));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 51, 51)));

        jPanel2.setBackground(new java.awt.Color(0, 136, 122));

        // setare imagine pentru jLabel2
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/copacregister.png")));
        jLabel2.setBackground(new java.awt.Color(0, 136, 122));
        jLabel2.setForeground(new java.awt.Color(0, 255, 204));
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 136, 122));

        jPanel_title.setBackground(new java.awt.Color(0, 136, 122));
        jPanel_title.setForeground(new java.awt.Color(0, 51, 51));

        jLabel1.setBackground(new java.awt.Color(0, 136, 122));
        jLabel1.setFont(new java.awt.Font("Bowlby One SC", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Wood Calculator");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        jLabel_fullname1.setBackground(new java.awt.Color(0, 136, 122));
        jLabel_fullname1.setForeground(new java.awt.Color(0, 136, 122));
        jLabel_fullname1.setOpaque(true);

        jLabel_backToLogin.setBackground(new java.awt.Color(0, 136, 122));
        jLabel_backToLogin.setForeground(new java.awt.Color(0, 136, 122));
        jLabel_backToLogin.setOpaque(true);
        jLabel_backToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_backToLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_backToLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_backToLoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_titleLayout = new javax.swing.GroupLayout(jPanel_title);
        jPanel_title.setLayout(jPanel_titleLayout);
        jPanel_titleLayout.setHorizontalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titleLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel_backToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_titleLayout.createSequentialGroup()
                    .addGap(214, 214, 214)
                    .addComponent(jLabel_fullname1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(214, Short.MAX_VALUE)))
        );
        jPanel_titleLayout.setVerticalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titleLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_backToLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(16, 16, 16))
            .addGroup(jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_titleLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jLabel_fullname1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(24, 24, 24)))
        );

        //setare imagine username
        jLabel_fullname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/fullname.png")));
        //setare imagine username
        jLabel_backToLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/back.png")));

        jLabel_close.setBackground(new java.awt.Color(0, 136, 122));
        jLabel_close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("x");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.setOpaque(true);
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });

        jPanel_minimize.setBackground(new java.awt.Color(0, 136, 122));
        jPanel_minimize.setForeground(new java.awt.Color(0, 51, 51));
        jPanel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_minimizeMouseExited(evt);
            }
        });

        jLabel_minimize.setBackground(new java.awt.Color(0, 136, 122));
        jLabel_minimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_minimize.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimize.setText("-");
        jLabel_minimize.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.setOpaque(true);
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_minimizeLayout = new javax.swing.GroupLayout(jPanel_minimize);
        jPanel_minimize.setLayout(jPanel_minimizeLayout);
        jPanel_minimizeLayout.setHorizontalGroup(
            jPanel_minimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_minimizeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_minimizeLayout.setVerticalGroup(
            jPanel_minimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_minimize, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jPanel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel_login_form.setBackground(new java.awt.Color(0, 136, 122));
        jPanel_login_form.setForeground(new java.awt.Color(0, 51, 51));

        jLabel3.setBackground(new java.awt.Color(0, 136, 122));

        jLabel4.setBackground(new java.awt.Color(0, 136, 122));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Inregistrare");

        jLabel_username.setBackground(new java.awt.Color(0, 136, 122));
        jLabel_username.setOpaque(true);

        jTextField_username.setBackground(new java.awt.Color(254, 250, 224));
        jTextField_username.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField_username.setForeground(new java.awt.Color(0, 51, 51));
        jTextField_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusLost(evt);
            }
        });

        jPasswordField_confirmpassword.setBackground(new java.awt.Color(254, 250, 224));
        jPasswordField_confirmpassword.setForeground(new java.awt.Color(0, 51, 51));
        jPasswordField_confirmpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_confirmpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_confirmpasswordFocusLost(evt);
            }
        });

        jButton_register.setBackground(new java.awt.Color(0, 102, 102));
        jButton_register.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jButton_register.setForeground(new java.awt.Color(0, 51, 51));
        jButton_register.setText("inregistrare");
        jButton_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_registerMouseExited(evt);
            }
        });
        jButton_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registerActionPerformed(evt);
            }
        });

        jLabel_fullname.setBackground(new java.awt.Color(0, 136, 122));
        jLabel_fullname.setForeground(new java.awt.Color(0, 136, 122));
        jLabel_fullname.setOpaque(true);

        jTextField_fullname.setBackground(new java.awt.Color(254, 250, 224));
        jTextField_fullname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField_fullname.setForeground(new java.awt.Color(0, 51, 51));
        jTextField_fullname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_fullnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_fullnameFocusLost(evt);
            }
        });

        jLabel_password.setBackground(new java.awt.Color(0, 136, 122));
        jLabel_password.setOpaque(true);

        jPasswordField_password.setBackground(new java.awt.Color(254, 250, 224));
        jPasswordField_password.setForeground(new java.awt.Color(0, 51, 51));
        jPasswordField_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_passwordFocusLost(evt);
            }
        });

        jLabel_telefon.setBackground(new java.awt.Color(0, 136, 122));
        jLabel_telefon.setOpaque(true);
        jLabel_telefon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_telefonMouseEntered(evt);
            }
        });

        jTextField_telefon.setBackground(new java.awt.Color(254, 250, 224));
        jTextField_telefon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField_telefon.setForeground(new java.awt.Color(0, 51, 51));
        jTextField_telefon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_telefonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_telefonFocusLost(evt);
            }
        });
        jTextField_telefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_telefonActionPerformed(evt);
            }
        });
        jTextField_telefon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_telefonKeyTyped(evt);
            }
        });

        jLabel_confirmpassword.setBackground(new java.awt.Color(0, 136, 122));
        jLabel_confirmpassword.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Bowlby One SC", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Nume");

        jLabel6.setFont(new java.awt.Font("Bowlby One SC", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("utilizator");

        jLabel7.setFont(new java.awt.Font("Bowlby One SC", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("parola");

        jLabel8.setFont(new java.awt.Font("Bowlby One SC", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("confirmare");

        jLabel9.setFont(new java.awt.Font("Bowlby One SC", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("telefon");

        javax.swing.GroupLayout jPanel_login_formLayout = new javax.swing.GroupLayout(jPanel_login_form);
        jPanel_login_form.setLayout(jPanel_login_formLayout);
        jPanel_login_formLayout.setHorizontalGroup(
            jPanel_login_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_login_formLayout.createSequentialGroup()
                .addGroup(jPanel_login_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_login_formLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel_confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField_confirmpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                    .addGroup(jPanel_login_formLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel_login_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_login_formLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_login_formLayout.createSequentialGroup()
                                .addGroup(jPanel_login_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_username, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_password, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_login_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_login_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordField_password)
                                    .addComponent(jTextField_username)
                                    .addComponent(jTextField_fullname)))))
                    .addGroup(jPanel_login_formLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_telefon)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_login_formLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_register, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel_login_formLayout.setVerticalGroup(
            jPanel_login_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_login_formLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel_login_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_login_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_fullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_fullname, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_login_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_login_formLayout.createSequentialGroup()
                        .addGroup(jPanel_login_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_username, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(jLabel_username, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_login_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordField_password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(jLabel_password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel_login_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_login_formLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordField_confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_login_formLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel_confirmpassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_login_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_telefon, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel_telefon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton_register, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        //setare imagine login
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/user1.png")));
        //setare imagine username
        jLabel_username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/user2.png")));
        //setare imagine username
        jLabel_fullname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/fullname.png")));
        //setare imagine login
        jLabel_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/password.png")));
        //setare imagine username
        jLabel_telefon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/telefon.png")));
        //setare imagine login
        jLabel_confirmpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/confirmpassword.png")));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_login_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jPanel_login_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        jLabel_close.setBackground(Color.red);
        jLabel_close.setForeground(Color.white);
        Border jLabel_close_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_close.setBorder(jLabel_close_border);

    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        jLabel_close.setBackground(new Color(0, 136, 122));
        jLabel_close.setForeground(new Color(0, 51, 51));
        Border jLabel_close_border = BorderFactory.createMatteBorder(0, 0, 0, 0, Color.black);
        jLabel_close.setBorder(jLabel_close_border);

    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered

        Border jLabel_minimize_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        //set border to the jLabel_minimize
        jLabel_minimize.setBorder(jLabel_minimize_border);
        jLabel_minimize.setBackground(new Color(254, 250, 224));

    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        jLabel_minimize.setBackground(new Color(0, 136, 122));
        Border jLabel_minimize_border = BorderFactory.createMatteBorder(0, 0, 0, 0, Color.black);
        jLabel_minimize.setBorder(jLabel_minimize_border);
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jPanel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_minimizeMouseEntered
        jPanel_minimize.setBackground(new Color(254, 250, 224));
    }//GEN-LAST:event_jPanel_minimizeMouseEntered

    private void jPanel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_minimizeMouseExited
        jPanel_minimize.setBackground(new Color(0, 136, 122));
    }//GEN-LAST:event_jPanel_minimizeMouseExited

    private void jTextField_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusGained
        ///curata textul din caseta daca este egal cu 'username'
        jLabel6.setForeground(new Color(254, 250, 224));
        jLabel_username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/user2green.png")));

        Border jTextField_username_border = BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(0, 51, 51));
        jTextField_username.setBorder(jTextField_username_border);
    }//GEN-LAST:event_jTextField_usernameFocusGained

    private void jTextField_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusLost
       
        jLabel_username.setBorder(null);
        jLabel_username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/user2.png")));
        jLabel6.setForeground(new Color(0, 51, 51));
        Border jTextField_username_border = BorderFactory.createMatteBorder(0, 0, 0, 0, new Color(0, 51, 51));
        jTextField_username.setBorder(jTextField_username_border);
    }//GEN-LAST:event_jTextField_usernameFocusLost

    private void jPasswordField_confirmpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_confirmpasswordFocusGained
        jLabel8.setForeground(new Color(254, 250, 224));
        jLabel_confirmpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/confirmpasswordgreen.png")));
        Border jPasswordField_password_border = BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(0, 51, 51));
        jPasswordField_confirmpassword.setBorder(jPasswordField_password_border);
    }//GEN-LAST:event_jPasswordField_confirmpasswordFocusGained

    private void jPasswordField_confirmpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_confirmpasswordFocusLost
        jLabel8.setForeground(new Color(0, 51, 51));
        jLabel_confirmpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/confirmpassword.png")));
        Border jPasswordField_password_border = BorderFactory.createMatteBorder(0, 0, 0, 0, new Color(0, 51, 51));
        jPasswordField_confirmpassword.setBorder(jPasswordField_password_border);

    }//GEN-LAST:event_jPasswordField_confirmpasswordFocusLost

    private void jButton_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_registerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_registerMouseClicked

    private void jButton_registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_registerMouseEntered
        //schimba culoarea butonului la plasarea cursorului pe el
        jButton_register.setBackground(new Color(254, 250, 224));
    }//GEN-LAST:event_jButton_registerMouseEntered

    private void jButton_registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_registerMouseExited
        // schimba culoarea butonului la parasirea cursorului de pe el
        jButton_register.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_jButton_registerMouseExited

    private void jButton_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registerActionPerformed
        String fname = jTextField_fullname.getText();
        String uname = jTextField_username.getText();
        String pass1 = String.valueOf(jPasswordField_password.getPassword());
        String pass2 = String.valueOf(jPasswordField_confirmpassword.getPassword());
        String tel = jTextField_telefon.getText();
        
        if(VerifyFields()){
            if(!CheckUsername(uname)){
                PreparedStatement ps;
                ResultSet rs;
                String registerUserQuery = "INSERT INTO `users`(`full_name`, `username`, `password`, `phone`) VALUES (?,?,?,?)";
                
                try{
                    
                    ps = My_CNX.getConnection().prepareStatement(registerUserQuery);
                    ps.setString(1, fname);
                    ps.setString(2, uname);
                    ps.setString(3, pass1);
                    ps.setString(4, tel);
                    try{
                        if(ps.executeUpdate() != 0){
                            JOptionPane.showMessageDialog(null, "Contul dumneavoastra a fost creat!");
                            LoginForm login = new LoginForm();
                            login.setVisible(true);
                            login.pack();
                            login.setLocationRelativeTo(null);
                            this.dispose();
                        }
                        else{
                             JOptionPane.showMessageDialog(null, "Error! Check Your Information!");
                        }
                    }
                    catch(SQLException ex){
                        Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE,null,ex);
                    }
                }
                catch(SQLException ex){
                     Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE,null,ex);
                     }
                
            }
        }
    }//GEN-LAST:event_jButton_registerActionPerformed

    private void jTextField_fullnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_fullnameFocusGained
        Border jTextField_fullname_border = BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(0, 51, 51));
        jTextField_fullname.setBorder(jTextField_fullname_border);
        jLabel5.setForeground(new Color(254, 250, 224));
        jLabel_fullname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/fullnamegreen.png")));
    }//GEN-LAST:event_jTextField_fullnameFocusGained

    private void jTextField_fullnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_fullnameFocusLost
        Border jTextField_fullname_border = BorderFactory.createMatteBorder(0, 0, 0, 0, new Color(0, 51, 51));
        jTextField_fullname.setBorder(jTextField_fullname_border);
        jLabel5.setForeground(new Color(0, 51, 51));
        jLabel_fullname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/fullname.png")));
    }//GEN-LAST:event_jTextField_fullnameFocusLost

    private void jPasswordField_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_passwordFocusGained
        jLabel_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/passwordgreen.png")));
        Border jTextField_password_border = BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(0, 51, 51));
        jPasswordField_password.setBorder(jTextField_password_border);
        jLabel7.setForeground(new Color(254, 250, 224));
    }//GEN-LAST:event_jPasswordField_passwordFocusGained

    private void jPasswordField_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_passwordFocusLost
       Border jTextField_password_border = BorderFactory.createMatteBorder(0, 0, 0, 0, new Color(0, 51, 51));
       jPasswordField_password.setBorder(jTextField_password_border);
       jLabel7.setForeground(new Color(0, 51, 51));
       jLabel_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/password.png")));
    }//GEN-LAST:event_jPasswordField_passwordFocusLost

    private void jTextField_telefonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_telefonFocusGained
        jLabel_telefon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/telefongreen.png"))); 
           Border jTextField_password_border = BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(0, 51, 51));
           jTextField_telefon.setBorder(jTextField_password_border);
           jLabel9.setForeground(new Color(254, 250, 224));
    }//GEN-LAST:event_jTextField_telefonFocusGained

    private void jTextField_telefonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_telefonFocusLost
        jLabel_telefon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/telefon.png"))); 
           Border jTextField_password_border = BorderFactory.createMatteBorder(0, 0, 0, 0, new Color(0, 51, 51));
           jTextField_telefon.setBorder(jTextField_password_border);
           jLabel9.setForeground(new Color(0, 51, 51));
    }//GEN-LAST:event_jTextField_telefonFocusLost

    private void jTextField_telefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_telefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_telefonActionPerformed

    private void jLabel_telefonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_telefonMouseEntered
           
    }//GEN-LAST:event_jLabel_telefonMouseEntered

    private void jTextField_telefonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_telefonKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume(); 
        }
    
    }//GEN-LAST:event_jTextField_telefonKeyTyped

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
                            LoginForm login = new LoginForm();
                            login.setVisible(true);
                            login.pack();
                            login.setLocationRelativeTo(null);
                            this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel_backToLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_backToLoginMouseClicked
        LoginForm login = new LoginForm();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel_backToLoginMouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setForeground(new Color(254, 250, 224));
        jLabel_backToLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/backred.png")));

    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel_backToLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_backToLoginMouseEntered
        jLabel1.setForeground(new Color(254, 250, 224));
        jLabel_backToLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/backred.png")));
    }//GEN-LAST:event_jLabel_backToLoginMouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jLabel1.setForeground(new Color(0, 51, 51));
        jLabel_backToLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/back.png")));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel_backToLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_backToLoginMouseExited
        jLabel1.setForeground(new Color(0, 51, 51));
        jLabel_backToLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/back.png")));
    }//GEN-LAST:event_jLabel_backToLoginMouseExited
    
    //functie care verifica daca toate campurile sunt completate
    public boolean VerifyFields()
    {
        String fname = jTextField_fullname.getText();
        String uname = jTextField_username.getText();
        String pass1 = String.valueOf(jPasswordField_password.getPassword());
        String pass2 = String.valueOf(jPasswordField_confirmpassword.getPassword());
        String tel = jTextField_telefon.getText();
        //verifica daca parolele sunt identice
        if(fname.trim().equals("") || uname.trim().equals("") || pass1.trim().equals("") || pass2.trim().equals("") || tel.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Unul sau mai multe câmpuri sunt goale!","Empty Fields",2);
            return false;
        }
        else{
            if(!pass1.equals(pass2)){
                 JOptionPane.showMessageDialog(null, "Parolele nu se potrivesc!","Confirm Password",2);
                 return false;
                }
            else{
                return true;
            }
        }
    }
    
    //fuctie care verifica daca username se afla in baza de date
    public boolean CheckUsername(String username){
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;
        String query = "SELECT * FROM `users` WHERE `username` = ?";
        
        try{
            st = My_CNX.getConnection().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
            
            if(rs.next()){
                username_exist = true;
                JOptionPane.showMessageDialog(null, " Utilizator existent! Vă rugăm completați alt nume de utilizator", "Username Failed", 2);
            }
        }
        catch(SQLException ex){
            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE,null,ex);
        }
                
        return username_exist;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RegisterForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_backToLogin;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_confirmpassword;
    private javax.swing.JLabel jLabel_fullname;
    private javax.swing.JLabel jLabel_fullname1;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_telefon;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_login_form;
    private javax.swing.JPanel jPanel_minimize;
    private javax.swing.JPanel jPanel_title;
    private javax.swing.JPasswordField jPasswordField_confirmpassword;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JTextField jTextField_fullname;
    private javax.swing.JTextField jTextField_telefon;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
